# Aplicación
spring.application.name=aulaCreativa
api.version=1.0.0
server.error.include-message=always
server.port=8080

# Perfil
spring.profiles.active=prod

    # --- BACKEND (MYSQL DOCKER) ---

    # --- Configuración MySQL Dockerizada ---

    # URL de conexión (localhost porque tu Java corre en tu PC y se conecta al puerto 3306 expuesto por Docker)
    spring.datasource.url=jdbc:mysql://localhost:3306/artia_db?allowPublicKeyRetrieval=true&useSSL=false
    spring.datasource.username=root
    spring.datasource.password=root

    # Driver específico
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    # Comportamiento de Hibernate
    # 'update' mantiene los datos y solo actualiza el esquema.
    # 'create' o 'create-drop' borra todo al reiniciar (cuidado en prod).
    spring.jpa.hibernate.ddl-auto=update

    # Mostrar SQL en consola (opcional, útil para debug)
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- FRONTEND / VIEWS (Thymeleaf) ---
    # Thymeleaf (desactivar cache en desarrollo)
    spring.thymeleaf.prefix=classpath:/templates/
    spring.thymeleaf.suffix=.html
    spring.thymeleaf.encoding=UTF-8
    spring.thymeleaf.cache=false

    # Mensajes / i18n
    spring.messages.encoding=UTF-8
    spring.messages.basename=messages

    # Logging general (dev)
    logging.level.org.springframework=DEBUG
    logging.level.org.springframework.web=DEBUG
    logging.level.org.springframework.web.servlet.view=DEBUG