-- 1. Creación de la tabla ALUMNOS
CREATE TABLE ALUMNOS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    direccion VARCHAR(500),

    fecha_nacimiento VARCHAR(20),   -- tu modelo usa String
    fecha_alta VARCHAR(20),         -- tu modelo usa String

    activo BOOLEAN NOT NULL,        -- isActivo

    created_at TIMESTAMP NOT NULL   -- LocalDateTime
);

-- 2. Secuencia opcional (para H2 o PostgreSQL si lo necesitas)
DROP SEQUENCE IF EXISTS ALUMNOS_SEQ;
CREATE SEQUENCE ALUMNOS_SEQ START WITH 100 INCREMENT BY 1;
