package es.etg.daw.dawes.java.web.aulaCreativa.aulaCreativa.infraestructure.db.jpa.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;@Entity
@Data
@AllArgsConstructor
@Builder
@Table(name = "ALUMNOS")



public class AlumnoEntity {
    // Usamos IDENTITY. H2 lo mapea a 'GENERATED BY DEFAULT AS IDENTITY'.
    // MySQL lo mapea a 'AUTO_INCREMENT'. Es el método más portable.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "nombre", nullable = false, length = 255)
    private String nombre;

    @Basic(optional = true)
    @Column(name = "apellidos", length = 1000)
    private String apellido;

    @Column(name = "dni", length = 9, unique = true)
    private String dni; 

    @Column(name = "email", length = 255)
    private String email;

    @Column(name = "telefono", length = 15)
    private String telefono;

    @Column(name = "direccion", length = 500)
    private String direccion;

    @Column(name = "fecha_alta")
    private LocalDateTime fecha_alta;

    @Column(name = "activo", nullable = false)
    private boolean activo;


    // Relación Many-to-One: Es el lado propietario (tendrá la FK)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoria_id", nullable = false) // Columna de clave foránea en la tabla Alumno
    private CategoriaEntity categoria;

    // --- Constructores ---
    public AlumnoEntity() {
    }

    // Constructor con campos (simplificado)
    public AlumnoEntity(Integer id, String nombre, BigDecimal precio, LocalDateTime fechaCreacion,
            CategoriaEntity categoria) {
        this.id = id;
        this.nombre = nombre;
        this.precio = precio;
        this.fechaCreacion = fechaCreacion;
        this.categoria = categoria;
    }


}
